#!/bin/sh

# custom X settings
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# keymapping
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

# custom fonts
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/TTF/
xset fp rehash

# turn off the annoying beep
xset b off

# start i3
# debug mode
#exec ck-launch-session dbus-launch --sh-syntax --exit-with-session i3 -V -d all >~/.i3/i3log-$(date +'%F-%k-%M-%S') 2>&1
exec ck-launch-session dbus-launch --sh-syntax --exit-with-session i3 
