#!/bin/sh

# EasyOBSD hotplugd attach script 0.1
# Mount easily mass storage device

# Copyright (c) 2009, Azwaw OUSADOU <bsdmaniak@gmail.com>
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

#       1) Redistributions of source code must retain the above copyright
#          notce, this list of conditions and the following disclaimer.
#       2) Redistributions in binary form must reproduce the above copyright
#          notice, this list of conditions and the following disclaimer in
#          the documentation and/or other materials provided with the
#          distribution.
#       3) Neither the name of EasyOBSD nor the names of its contributors may
#          be used to endorse or promote products derived from this software
#          without specific prior written permission.


DEVCLASS=$1
DEVNAME=$2

log_hotplugd () {
          local LOG_DIR="/var/log/hotplugd"
          LOG_FILE="$LOG_DIR/attach"
          [ -d "$LOG_DIR" ] || mkdir -p "$LOG_DIR" && chown :bin "$LOG_DIR"
}

mount_device () {
          NAME=$(disklabel ${DEVNAME} | grep label | sed -n 's/label:\ //p')

          disklabel $DEVNAME | grep -v swap | grep -v unused | \
          grep -v unknown | grep \ \ [a-z]: | sed -n 's/://p'  | \
          awk '{ print $1" "$4 }' | \
          while read PART FS_DISKLABEL; do
		  echo "[DEBUG] Label $FS_DISKLABEL"  >> $LOG_FILE 2>&1
                  case $FS_DISKLABEL in
                  4.2BSD)
                          FS_MOUNT=ffs
                          MOUNT_ARGS="-m 777"
                          ;;
                  MSDOS)
                          FS_MOUNT=msdos
                          MOUNT_ARGS="-m 777"
                          ;;
                  NTFS)
                          FS_MOUNT=ntfs
                          MOUNT_ARGS="-o rdonly"
                          ;;
                  ISO9660)
                          FS_MOUNT=cd9660
                          MOUNT_ARGS=""
                          ;;
                  ext2fs)
                          FS_MOUNT=ext2fs
                          MOUNT_ARGS="-m 777"
                          ;;
                  *)
                          echo "File System Unsupported" 2>&1
                          continue;
                          ;;
                  esac
  
          case $FS_MOUNT in
          ntfs | cd9660)
                  echo "Read-Only File System: No Fsck" 2>&1
                  ;;
          *)
                  fsck_$FS_MOUNT -p /dev/${DEVNAME}${PART}
                  ;;
          esac

          mkdir /mnt/${DEVNAME}${PART}
          mount_$FS_MOUNT /dev/${DEVNAME}${PART} /mnt/${DEVNAME}${PART}

          for DIR in $(find /home/* -maxdepth 0 -type d); do
                  mkdir $DIR/Desktop
                  echo "[Desktop Entry]" >> $DIR/Desktop/${DEVNAME}${PART}.desktop
                  echo Name=${DEVNAME}${PART} >> $DIR/Desktop/${DEVNAME}${PART}.desktop
                  echo Type=Application >> $DIR/Desktop/${DEVNAME}${PART}.desktop
                  echo Icon=harddrive >> $DIR/Desktop/${DEVNAME}${PART}.desktop
                  echo Exec=thunar /mnt/${DEVNAME}${PART} >> $DIR/Desktop/${DEVNAME}${PART}.desktop
                  #echo Dev=/dev/${DEVNAME}${PART} >> $DIR/Desktop/${DEVNAME}${PART}.desktop
                  #echo MountPoint=/mnt/${DEVNAME}${PART} >> $DIR/Desktop/${DEVNAME}${PART}.desktop
                  #echo Type=FSDevice >> $DIR/Desktop/${DEVNAME}${PART}.desktop
                  chmod +x $DIR/Desktop/${DEVNAME}${PART}.desktop
          done

          done
}

log_hotplugd

echo "[DEBUG] mount $DEVNAME => class $DEVCLASS"  >> $LOG_FILE 2>&1
case $DEVCLASS in
  2)
          echo Mount at `date`
          mount_device >> $LOG_FILE 2>&1
          ;;
esac
