#!/bin/sh

# EasyOBSD hotplugd detach script 0.1
# Umount easily mass storage device

# Copyright (c) 2009, Azwaw OUSADOU <bsdmaniak@gmail.com>
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

#       1) Redistributions of source code must retain the above copyright
#          notce, this list of conditions and the following disclaimer.
#       2) Redistributions in binary form must reproduce the above copyright
#          notice, this list of conditions and the following disclaimer in
#          the documentation and/or other materials provided with the
#          distribution.
#       3) Neither the name of EasyOBSD nor the names of its contributors may
#          be used to endorse or promote products derived from this software
#          without specific prior written permission.

DEVCLASS=$1
DEVNAME=$2

log_hotplugd () {
          local LOG_DIR="/var/log/hotplugd"
          LOG_FILE="$LOG_DIR/detach"
          [ -d "$LOG_DIR" ] || mkdir -p "$LOG_DIR" && chown :bin "$LOG_DIR"
}

umount_device () {
          for DIR in $(find /mnt/$DEVNAME* -maxdepth 0); do
                  umount -f $DIR
                  rm -rf $DIR
          done

          for DIR in $(find /home/* -maxdepth 0 -type d); do
                  rm $DIR/Desktop/$DEVNAME*.desktop
          done
}

log_hotplugd

case $DEVCLASS in
  2)
          echo Umount At `date` 2>&1
          umount_device >> $LOG_FILE 2>&1
          ;;
esac
